# Generated by Django 3.1.5 on 2021-01-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='lname',
        ),
    ]
